### ISSUE TITLE
Minskins 07-10

### ISSUE THREAD

**Issue by Bismarck-GM** [sanadwj/ror-social-scaffold#4]
Nice job with the project !

You are almost there 🥇 

@Adfpizarro: You should use the friendship request id to accept a friend instead of sending the user-id witch can be duplicated.

Have a spicy wednesday.

![FRIENDSHIP](https://media.giphy.com/media/OWO47ARzqerTO/giphy.gif)

**Comment by sanadwj** [comment]
Thanks
